version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./.env:/var/www/.env
            - auction_app_appfiles:/var/www
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - APP_KEY=${APP_KEY}
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=laravel
            - DB_USERNAME=laravel
            - DB_PASSWORD=laravel
            - SESSION_DRIVER=file
        networks:
            - auction_app
        depends_on:
            - db

    web:
        image: nginx:latest
        restart: unless-stopped

        ports:
            - "2010:80"
        volumes:
            - ./default.conf:/etc/nginx/conf.d/default.conf
            - auction_app_appfiles:/var/www
        networks:
            - auction_app
        depends_on:
            - app

    db:
        image: mysql:8.0
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel
        volumes:
            - auction_app_dbdata:/var/lib/mysql
        # ports:
        #     - "3308:3306"
        networks:
            - auction_app
    node:
        image: node:18
        working_dir: /var/www
        volumes:
            - auction_app_appfiles:/var/www
        command: sh -c "rm -R node_modules && npm install && npm run build"
        networks:
            - auction_app

volumes:
    auction_app_dbdata:
    auction_app_appfiles:

networks:
    auction_app:
